version: 2
models:
  - name: stg_telegram_messages
    description: "Staging table for Telegram messages"
    columns:
      - name: message_id
        description: "Unique ID for each message"
        tests:
          - unique
          - not_null
      - name: message_date
        description: "Date of the message"
        tests:
          - not_null
